name: BigBrother
version: 1.5.1-beta
api: [1.12.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
author: shoghicp
website: https://github.com/shoghicp/BigBrother
load: STARTUP
main: shoghicp\BigBrother\BigBrother
softdepend:
 - SimpleAuth
